<?xml version="1.0" encoding="utf-8"?><Database Name="KFC_DB" Class="KFCDatabaseClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=&quot;D:\2011-2012\Software analysis and design\Group-work\Project_SVN\1 Document\Thao\KFC Database\KFC_DB.mdf&quot;;Integrated Security=True;Connect Timeout=30;User Instance=True" SettingsObjectName="ServiceLibrary.Properties.Settings" SettingsPropertyName="KFC_DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BILL" Member="BILLs">
    <Type Name="BILL">
      <Column Name="BillID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BillDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BillStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeleteNote" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EmpID" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Association Name="EMPLOYEE_BILL" Member="EMPLOYEE" ThisKey="EmpID" OtherKey="EmpID" Type="EMPLOYEE" IsForeignKey="true" />
      <Association Name="ORDER__BILL" Member="ORDER_" ThisKey="OrderID" OtherKey="OrderID" Type="ORDER_" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WARNING" Member="WARNINGs">
    <Type Name="WARNING">
      <Column Name="WarningID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WarningName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.EMPLOYEE" Member="EMPLOYEEs">
    <Type Name="EMPLOYEE">
      <Column Name="EmpID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PositionID" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="EMPLOYEE_BILL" Member="BILLs" ThisKey="EmpID" OtherKey="EmpID" Type="BILL" />
      <Association Name="EMPLOYEE_INFO_EMPLOYEE" Member="EMPLOYEE_INFO" ThisKey="EmpID" OtherKey="EmpID" Type="EMPLOYEE_INFO" IsForeignKey="true" />
      <Association Name="PERMISSION_EMPLOYEE" Member="PERMISSION" ThisKey="PositionID" OtherKey="PositionID" Type="PERMISSION" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EMPLOYEE_INFO" Member="EMPLOYEE_INFOs">
    <Type Name="EMPLOYEE_INFO">
      <Column Name="EmpID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmpName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Sex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="EMPLOYEE_INFO_EMPLOYEE" Member="EMPLOYEE" ThisKey="EmpID" OtherKey="EmpID" Type="EMPLOYEE" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.FOOD" Member="FOODs">
    <Type Name="FOOD">
      <Column Name="FoodID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FoodName" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FoodPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiscountPrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FoodGroupID" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Association Name="FOOD_ORDER_DETAIL" Member="ORDER_DETAILs" ThisKey="FoodID" OtherKey="FoodID" Type="ORDER_DETAIL" />
      <Association Name="FOOD_GROUP_FOOD" Member="FOOD_GROUP" ThisKey="FoodGroupID" OtherKey="FoodGroupID" Type="FOOD_GROUP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FOOD_GROUP" Member="FOOD_GROUPs">
    <Type Name="FOOD_GROUP">
      <Column Name="FoodGroupID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FoodGroupName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="FOOD_GROUP_FOOD" Member="FOODs" ThisKey="FoodGroupID" OtherKey="FoodGroupID" Type="FOOD" />
    </Type>
  </Table>
  <Table Name="dbo.ORDER_" Member="ORDER_s">
    <Type Name="ORDER_">
      <Column Name="OrderID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TableNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderNote" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="ORDER__BILL" Member="BILLs" ThisKey="OrderID" OtherKey="OrderID" Type="BILL" />
      <Association Name="ORDER__ORDER_DETAIL" Member="ORDER_DETAILs" ThisKey="OrderID" OtherKey="OrderID" Type="ORDER_DETAIL" />
    </Type>
  </Table>
  <Table Name="dbo.ORDER_DETAIL" Member="ORDER_DETAILs">
    <Type Name="ORDER_DETAIL">
      <Column Name="OrderID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FoodID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompleteTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FoodNote" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="FOOD_ORDER_DETAIL" Member="FOOD" ThisKey="FoodID" OtherKey="FoodID" Type="FOOD" IsForeignKey="true" />
      <Association Name="ORDER__ORDER_DETAIL" Member="ORDER_" ThisKey="OrderID" OtherKey="OrderID" Type="ORDER_" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PARAMETER" Member="PARAMETERs">
    <Type Name="PARAMETER">
      <Column Name="ParaID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Value" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PERMISSION" Member="PERMISSIONs">
    <Type Name="PERMISSION">
      <Column Name="PositionID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Permission" Member="Permission1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="PERMISSION_EMPLOYEE" Member="EMPLOYEEs" ThisKey="PositionID" OtherKey="PositionID" Type="EMPLOYEE" />
    </Type>
  </Table>
</Database>