//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class OrderDetailDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime CompleteTimeField;
        
        private string FoodIDField;
        
        private string FoodNoteField;
        
        private string OrderIDField;
        
        private int PriorityField;
        
        private int QuantityField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CompleteTime
        {
            get
            {
                return this.CompleteTimeField;
            }
            set
            {
                this.CompleteTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodID
        {
            get
            {
                return this.FoodIDField;
            }
            set
            {
                this.FoodIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodNote
        {
            get
            {
                return this.FoodNoteField;
            }
            set
            {
                this.FoodNoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class BillDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime BillDateField;
        
        private string BillIDField;
        
        private int BillStatusField;
        
        private string DeleteNoteField;
        
        private string EmpIDField;
        
        private string OrderIDField;
        
        private float TotalField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BillDate
        {
            get
            {
                return this.BillDateField;
            }
            set
            {
                this.BillDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillID
        {
            get
            {
                return this.BillIDField;
            }
            set
            {
                this.BillIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BillStatus
        {
            get
            {
                return this.BillStatusField;
            }
            set
            {
                this.BillStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeleteNote
        {
            get
            {
                return this.DeleteNoteField;
            }
            set
            {
                this.DeleteNoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpID
        {
            get
            {
                return this.EmpIDField;
            }
            set
            {
                this.EmpIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderFoodDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class OrderFoodDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DiscountPriceField;
        
        private string FoodIDField;
        
        private string FoodNameField;
        
        private int FoodPriceField;
        
        private int quantityField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiscountPrice
        {
            get
            {
                return this.DiscountPriceField;
            }
            set
            {
                this.DiscountPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodID
        {
            get
            {
                return this.FoodIDField;
            }
            set
            {
                this.FoodIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodName
        {
            get
            {
                return this.FoodNameField;
            }
            set
            {
                this.FoodNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FoodPrice
        {
            get
            {
                return this.FoodPriceField;
            }
            set
            {
                this.FoodPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class OrderDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime OrderDateField;
        
        private string OrderIDField;
        
        private string OrderNoteField;
        
        private int OrderStatusField;
        
        private int TableNumField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate
        {
            get
            {
                return this.OrderDateField;
            }
            set
            {
                this.OrderDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNote
        {
            get
            {
                return this.OrderNoteField;
            }
            set
            {
                this.OrderNoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderStatus
        {
            get
            {
                return this.OrderStatusField;
            }
            set
            {
                this.OrderStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TableNum
        {
            get
            {
                return this.TableNumField;
            }
            set
            {
                this.TableNumField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DailyReportDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class DailyReportDTO : DTO.ReportDTO
    {
        
        private string foodIDField;
        
        private string foodNameField;
        
        private int quantityField;
        
        private int totalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string foodID
        {
            get
            {
                return this.foodIDField;
            }
            set
            {
                this.foodIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string foodName
        {
            get
            {
                return this.foodNameField;
            }
            set
            {
                this.foodNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DTO.MonthlyReportDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DTO.YearlyReportDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DTO.DailyReportDTO))]
    public partial class ReportDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonthlyReportDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class MonthlyReportDTO : DTO.ReportDTO
    {
        
        private string billDateField;
        
        private int totalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string billDate
        {
            get
            {
                return this.billDateField;
            }
            set
            {
                this.billDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YearlyReportDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class YearlyReportDTO : DTO.ReportDTO
    {
        
        private string billDateField;
        
        private int totalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string billDate
        {
            get
            {
                return this.billDateField;
            }
            set
            {
                this.billDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class ClientDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private DTO.ClientType ClientTypeField;
        
        private string IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DTO.ClientType ClientType
        {
            get
            {
                return this.ClientTypeField;
            }
            set
            {
                this.ClientTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientType", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public enum ClientType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Table = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kitchen = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cashier = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoodDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class FoodDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private float DiscountPriceField;
        
        private string FoodGroupIDField;
        
        private string FoodIDField;
        
        private string FoodNameField;
        
        private float FoodPriceField;
        
        private string ImageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float DiscountPrice
        {
            get
            {
                return this.DiscountPriceField;
            }
            set
            {
                this.DiscountPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodGroupID
        {
            get
            {
                return this.FoodGroupIDField;
            }
            set
            {
                this.FoodGroupIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodID
        {
            get
            {
                return this.FoodIDField;
            }
            set
            {
                this.FoodIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodName
        {
            get
            {
                return this.FoodNameField;
            }
            set
            {
                this.FoodNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FoodPrice
        {
            get
            {
                return this.FoodPriceField;
            }
            set
            {
                this.FoodPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                this.ImageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoodGroupDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class FoodGroupDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FoodGroupIDField;
        
        private string FoodGroupNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodGroupID
        {
            get
            {
                return this.FoodGroupIDField;
            }
            set
            {
                this.FoodGroupIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodGroupName
        {
            get
            {
                return this.FoodGroupNameField;
            }
            set
            {
                this.FoodGroupNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService", CallbackContract=typeof(IServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface IService
{
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectOrderDetailById", ReplyAction="http://tempuri.org/IService/SelectOrderDetailByIdResponse")]
    DTO.OrderDetailDTO[] SelectOrderDetailById(string orderId, string foodId);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectOrderDetailById", ReplyAction="http://tempuri.org/IService/SelectOrderDetailByIdResponse")]
    System.IAsyncResult BeginSelectOrderDetailById(string orderId, string foodId, System.AsyncCallback callback, object asyncState);
    
    DTO.OrderDetailDTO[] EndSelectOrderDetailById(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addBill", ReplyAction="http://tempuri.org/IService/addBillResponse")]
    bool addBill(DTO.BillDTO billDTO);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addBill", ReplyAction="http://tempuri.org/IService/addBillResponse")]
    System.IAsyncResult BeginaddBill(DTO.BillDTO billDTO, System.AsyncCallback callback, object asyncState);
    
    bool EndaddBill(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteBillByDTO", ReplyAction="http://tempuri.org/IService/DeleteBillByDTOResponse")]
    bool DeleteBillByDTO(DTO.BillDTO billDTO);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteBillByDTO", ReplyAction="http://tempuri.org/IService/DeleteBillByDTOResponse")]
    System.IAsyncResult BeginDeleteBillByDTO(DTO.BillDTO billDTO, System.AsyncCallback callback, object asyncState);
    
    bool EndDeleteBillByDTO(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteBillById", ReplyAction="http://tempuri.org/IService/DeleteBillByIdResponse")]
    bool DeleteBillById(string billID);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteBillById", ReplyAction="http://tempuri.org/IService/DeleteBillByIdResponse")]
    System.IAsyncResult BeginDeleteBillById(string billID, System.AsyncCallback callback, object asyncState);
    
    bool EndDeleteBillById(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectBillByDTO", ReplyAction="http://tempuri.org/IService/SelectBillByDTOResponse")]
    DTO.BillDTO[] SelectBillByDTO(DTO.BillDTO billDTO);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectBillByDTO", ReplyAction="http://tempuri.org/IService/SelectBillByDTOResponse")]
    System.IAsyncResult BeginSelectBillByDTO(DTO.BillDTO billDTO, System.AsyncCallback callback, object asyncState);
    
    DTO.BillDTO[] EndSelectBillByDTO(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectBillById", ReplyAction="http://tempuri.org/IService/SelectBillByIdResponse")]
    DTO.BillDTO[] SelectBillById(string billID);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectBillById", ReplyAction="http://tempuri.org/IService/SelectBillByIdResponse")]
    System.IAsyncResult BeginSelectBillById(string billID, System.AsyncCallback callback, object asyncState);
    
    DTO.BillDTO[] EndSelectBillById(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getEmpIdAndPermission", ReplyAction="http://tempuri.org/IService/getEmpIdAndPermissionResponse")]
    string[] getEmpIdAndPermission(string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getEmpIdAndPermission", ReplyAction="http://tempuri.org/IService/getEmpIdAndPermissionResponse")]
    System.IAsyncResult BegingetEmpIdAndPermission(string username, string password, System.AsyncCallback callback, object asyncState);
    
    string[] EndgetEmpIdAndPermission(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getPermission", ReplyAction="http://tempuri.org/IService/getPermissionResponse")]
    string getPermission(string empId);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getPermission", ReplyAction="http://tempuri.org/IService/getPermissionResponse")]
    System.IAsyncResult BegingetPermission(string empId, System.AsyncCallback callback, object asyncState);
    
    string EndgetPermission(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/viewFoodDetail", ReplyAction="http://tempuri.org/IService/viewFoodDetailResponse")]
    DTO.OrderFoodDTO[] viewFoodDetail(string orderID);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/viewFoodDetail", ReplyAction="http://tempuri.org/IService/viewFoodDetailResponse")]
    System.IAsyncResult BeginviewFoodDetail(string orderID, System.AsyncCallback callback, object asyncState);
    
    DTO.OrderFoodDTO[] EndviewFoodDetail(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/viewOrderInfo", ReplyAction="http://tempuri.org/IService/viewOrderInfoResponse")]
    DTO.OrderDTO viewOrderInfo(int tableNum);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/viewOrderInfo", ReplyAction="http://tempuri.org/IService/viewOrderInfoResponse")]
    System.IAsyncResult BeginviewOrderInfo(int tableNum, System.AsyncCallback callback, object asyncState);
    
    DTO.OrderDTO EndviewOrderInfo(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getUnfreeTable", ReplyAction="http://tempuri.org/IService/getUnfreeTableResponse")]
    DTO.OrderDTO[] getUnfreeTable(int floorNum);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getUnfreeTable", ReplyAction="http://tempuri.org/IService/getUnfreeTableResponse")]
    System.IAsyncResult BegingetUnfreeTable(int floorNum, System.AsyncCallback callback, object asyncState);
    
    DTO.OrderDTO[] EndgetUnfreeTable(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getEmployeeName", ReplyAction="http://tempuri.org/IService/getEmployeeNameResponse")]
    string getEmployeeName(string empID);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getEmployeeName", ReplyAction="http://tempuri.org/IService/getEmployeeNameResponse")]
    System.IAsyncResult BegingetEmployeeName(string empID, System.AsyncCallback callback, object asyncState);
    
    string EndgetEmployeeName(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getTotalOfDay", ReplyAction="http://tempuri.org/IService/getTotalOfDayResponse")]
    int getTotalOfDay(System.DateTime billDate);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getTotalOfDay", ReplyAction="http://tempuri.org/IService/getTotalOfDayResponse")]
    System.IAsyncResult BegingetTotalOfDay(System.DateTime billDate, System.AsyncCallback callback, object asyncState);
    
    int EndgetTotalOfDay(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getDailyReport", ReplyAction="http://tempuri.org/IService/getDailyReportResponse")]
    DTO.DailyReportDTO[] getDailyReport(System.DateTime billDate);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getDailyReport", ReplyAction="http://tempuri.org/IService/getDailyReportResponse")]
    System.IAsyncResult BegingetDailyReport(System.DateTime billDate, System.AsyncCallback callback, object asyncState);
    
    DTO.DailyReportDTO[] EndgetDailyReport(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getTotalOfMonth", ReplyAction="http://tempuri.org/IService/getTotalOfMonthResponse")]
    int getTotalOfMonth(System.DateTime billDate);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getTotalOfMonth", ReplyAction="http://tempuri.org/IService/getTotalOfMonthResponse")]
    System.IAsyncResult BegingetTotalOfMonth(System.DateTime billDate, System.AsyncCallback callback, object asyncState);
    
    int EndgetTotalOfMonth(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getMonthlyReport", ReplyAction="http://tempuri.org/IService/getMonthlyReportResponse")]
    DTO.MonthlyReportDTO[] getMonthlyReport(System.DateTime billDate);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getMonthlyReport", ReplyAction="http://tempuri.org/IService/getMonthlyReportResponse")]
    System.IAsyncResult BegingetMonthlyReport(System.DateTime billDate, System.AsyncCallback callback, object asyncState);
    
    DTO.MonthlyReportDTO[] EndgetMonthlyReport(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getTotalOfYear", ReplyAction="http://tempuri.org/IService/getTotalOfYearResponse")]
    int getTotalOfYear(System.DateTime billDate);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getTotalOfYear", ReplyAction="http://tempuri.org/IService/getTotalOfYearResponse")]
    System.IAsyncResult BegingetTotalOfYear(System.DateTime billDate, System.AsyncCallback callback, object asyncState);
    
    int EndgetTotalOfYear(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getYearlyReport", ReplyAction="http://tempuri.org/IService/getYearlyReportResponse")]
    DTO.YearlyReportDTO[] getYearlyReport(System.DateTime billDate);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getYearlyReport", ReplyAction="http://tempuri.org/IService/getYearlyReportResponse")]
    System.IAsyncResult BegingetYearlyReport(System.DateTime billDate, System.AsyncCallback callback, object asyncState);
    
    DTO.YearlyReportDTO[] EndgetYearlyReport(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/connect", ReplyAction="http://tempuri.org/IService/connectResponse")]
    bool connect(DTO.ClientDTO client);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/connect", ReplyAction="http://tempuri.org/IService/connectResponse")]
    System.IAsyncResult Beginconnect(DTO.ClientDTO client, System.AsyncCallback callback, object asyncState);
    
    bool Endconnect(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/NewOrderInService", ReplyAction="http://tempuri.org/IService/NewOrderInServiceResponse")]
    void NewOrderInService();
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/NewOrderInService", ReplyAction="http://tempuri.org/IService/NewOrderInServiceResponse")]
    System.IAsyncResult BeginNewOrderInService(System.AsyncCallback callback, object asyncState);
    
    void EndNewOrderInService(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addFood", ReplyAction="http://tempuri.org/IService/addFoodResponse")]
    bool addFood(DTO.FoodDTO foodDTO);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addFood", ReplyAction="http://tempuri.org/IService/addFoodResponse")]
    System.IAsyncResult BeginaddFood(DTO.FoodDTO foodDTO, System.AsyncCallback callback, object asyncState);
    
    bool EndaddFood(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteFoodByDTO", ReplyAction="http://tempuri.org/IService/DeleteFoodByDTOResponse")]
    bool DeleteFoodByDTO(DTO.FoodDTO foodDTO);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteFoodByDTO", ReplyAction="http://tempuri.org/IService/DeleteFoodByDTOResponse")]
    System.IAsyncResult BeginDeleteFoodByDTO(DTO.FoodDTO foodDTO, System.AsyncCallback callback, object asyncState);
    
    bool EndDeleteFoodByDTO(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteFoodByID", ReplyAction="http://tempuri.org/IService/DeleteFoodByIDResponse")]
    bool DeleteFoodByID(string foodID);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteFoodByID", ReplyAction="http://tempuri.org/IService/DeleteFoodByIDResponse")]
    System.IAsyncResult BeginDeleteFoodByID(string foodID, System.AsyncCallback callback, object asyncState);
    
    bool EndDeleteFoodByID(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/updateFood", ReplyAction="http://tempuri.org/IService/updateFoodResponse")]
    bool updateFood(DTO.FoodDTO newInfo);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/updateFood", ReplyAction="http://tempuri.org/IService/updateFoodResponse")]
    System.IAsyncResult BeginupdateFood(DTO.FoodDTO newInfo, System.AsyncCallback callback, object asyncState);
    
    bool EndupdateFood(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectFoodByDTO", ReplyAction="http://tempuri.org/IService/SelectFoodByDTOResponse")]
    DTO.FoodDTO[] SelectFoodByDTO(DTO.FoodDTO foodDTO);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectFoodByDTO", ReplyAction="http://tempuri.org/IService/SelectFoodByDTOResponse")]
    System.IAsyncResult BeginSelectFoodByDTO(DTO.FoodDTO foodDTO, System.AsyncCallback callback, object asyncState);
    
    DTO.FoodDTO[] EndSelectFoodByDTO(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectFoodById", ReplyAction="http://tempuri.org/IService/SelectFoodByIdResponse")]
    DTO.FoodDTO[] SelectFoodById(string foodID);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectFoodById", ReplyAction="http://tempuri.org/IService/SelectFoodByIdResponse")]
    System.IAsyncResult BeginSelectFoodById(string foodID, System.AsyncCallback callback, object asyncState);
    
    DTO.FoodDTO[] EndSelectFoodById(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addFoodGroup", ReplyAction="http://tempuri.org/IService/addFoodGroupResponse")]
    bool addFoodGroup(DTO.FoodGroupDTO foodGroupDTO);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addFoodGroup", ReplyAction="http://tempuri.org/IService/addFoodGroupResponse")]
    System.IAsyncResult BeginaddFoodGroup(DTO.FoodGroupDTO foodGroupDTO, System.AsyncCallback callback, object asyncState);
    
    bool EndaddFoodGroup(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteFoodGroupByDTO", ReplyAction="http://tempuri.org/IService/DeleteFoodGroupByDTOResponse")]
    bool DeleteFoodGroupByDTO(DTO.FoodGroupDTO foodGroupDTO);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteFoodGroupByDTO", ReplyAction="http://tempuri.org/IService/DeleteFoodGroupByDTOResponse")]
    System.IAsyncResult BeginDeleteFoodGroupByDTO(DTO.FoodGroupDTO foodGroupDTO, System.AsyncCallback callback, object asyncState);
    
    bool EndDeleteFoodGroupByDTO(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteFoodGroupById", ReplyAction="http://tempuri.org/IService/DeleteFoodGroupByIdResponse")]
    bool DeleteFoodGroupById(string foodGroupID);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteFoodGroupById", ReplyAction="http://tempuri.org/IService/DeleteFoodGroupByIdResponse")]
    System.IAsyncResult BeginDeleteFoodGroupById(string foodGroupID, System.AsyncCallback callback, object asyncState);
    
    bool EndDeleteFoodGroupById(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/updateFoodGroup", ReplyAction="http://tempuri.org/IService/updateFoodGroupResponse")]
    bool updateFoodGroup(DTO.FoodGroupDTO newInfo);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/updateFoodGroup", ReplyAction="http://tempuri.org/IService/updateFoodGroupResponse")]
    System.IAsyncResult BeginupdateFoodGroup(DTO.FoodGroupDTO newInfo, System.AsyncCallback callback, object asyncState);
    
    bool EndupdateFoodGroup(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectFoodGroupByDTO", ReplyAction="http://tempuri.org/IService/SelectFoodGroupByDTOResponse")]
    DTO.FoodGroupDTO[] SelectFoodGroupByDTO(DTO.FoodGroupDTO foodGroupDTO);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectFoodGroupByDTO", ReplyAction="http://tempuri.org/IService/SelectFoodGroupByDTOResponse")]
    System.IAsyncResult BeginSelectFoodGroupByDTO(DTO.FoodGroupDTO foodGroupDTO, System.AsyncCallback callback, object asyncState);
    
    DTO.FoodGroupDTO[] EndSelectFoodGroupByDTO(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectFoodGroupById", ReplyAction="http://tempuri.org/IService/SelectFoodGroupByIdResponse")]
    DTO.FoodGroupDTO[] SelectFoodGroupById(string foodGroupID);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectFoodGroupById", ReplyAction="http://tempuri.org/IService/SelectFoodGroupByIdResponse")]
    System.IAsyncResult BeginSelectFoodGroupById(string foodGroupID, System.AsyncCallback callback, object asyncState);
    
    DTO.FoodGroupDTO[] EndSelectFoodGroupById(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addOrder", ReplyAction="http://tempuri.org/IService/addOrderResponse")]
    bool addOrder(DTO.OrderDTO orderDTO);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addOrder", ReplyAction="http://tempuri.org/IService/addOrderResponse")]
    System.IAsyncResult BeginaddOrder(DTO.OrderDTO orderDTO, System.AsyncCallback callback, object asyncState);
    
    bool EndaddOrder(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteOrderByDTO", ReplyAction="http://tempuri.org/IService/DeleteOrderByDTOResponse")]
    bool DeleteOrderByDTO(DTO.OrderDTO orderDTO);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteOrderByDTO", ReplyAction="http://tempuri.org/IService/DeleteOrderByDTOResponse")]
    System.IAsyncResult BeginDeleteOrderByDTO(DTO.OrderDTO orderDTO, System.AsyncCallback callback, object asyncState);
    
    bool EndDeleteOrderByDTO(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteOrderById", ReplyAction="http://tempuri.org/IService/DeleteOrderByIdResponse")]
    bool DeleteOrderById(string orderID);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteOrderById", ReplyAction="http://tempuri.org/IService/DeleteOrderByIdResponse")]
    System.IAsyncResult BeginDeleteOrderById(string orderID, System.AsyncCallback callback, object asyncState);
    
    bool EndDeleteOrderById(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/updateOrder", ReplyAction="http://tempuri.org/IService/updateOrderResponse")]
    bool updateOrder(DTO.OrderDTO newInfo);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/updateOrder", ReplyAction="http://tempuri.org/IService/updateOrderResponse")]
    System.IAsyncResult BeginupdateOrder(DTO.OrderDTO newInfo, System.AsyncCallback callback, object asyncState);
    
    bool EndupdateOrder(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectOrderByDTO", ReplyAction="http://tempuri.org/IService/SelectOrderByDTOResponse")]
    DTO.OrderDTO[] SelectOrderByDTO(DTO.OrderDTO orderDTO);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectOrderByDTO", ReplyAction="http://tempuri.org/IService/SelectOrderByDTOResponse")]
    System.IAsyncResult BeginSelectOrderByDTO(DTO.OrderDTO orderDTO, System.AsyncCallback callback, object asyncState);
    
    DTO.OrderDTO[] EndSelectOrderByDTO(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectOrderById", ReplyAction="http://tempuri.org/IService/SelectOrderByIdResponse")]
    DTO.OrderDTO[] SelectOrderById(string orderID);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectOrderById", ReplyAction="http://tempuri.org/IService/SelectOrderByIdResponse")]
    System.IAsyncResult BeginSelectOrderById(string orderID, System.AsyncCallback callback, object asyncState);
    
    DTO.OrderDTO[] EndSelectOrderById(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addOrderDetail", ReplyAction="http://tempuri.org/IService/addOrderDetailResponse")]
    bool addOrderDetail(DTO.OrderDetailDTO orderDetailDTO);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addOrderDetail", ReplyAction="http://tempuri.org/IService/addOrderDetailResponse")]
    System.IAsyncResult BeginaddOrderDetail(DTO.OrderDetailDTO orderDetailDTO, System.AsyncCallback callback, object asyncState);
    
    bool EndaddOrderDetail(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteOrderDetailByDTO", ReplyAction="http://tempuri.org/IService/DeleteOrderDetailByDTOResponse")]
    bool DeleteOrderDetailByDTO(DTO.OrderDetailDTO orderDetailDTO);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteOrderDetailByDTO", ReplyAction="http://tempuri.org/IService/DeleteOrderDetailByDTOResponse")]
    System.IAsyncResult BeginDeleteOrderDetailByDTO(DTO.OrderDetailDTO orderDetailDTO, System.AsyncCallback callback, object asyncState);
    
    bool EndDeleteOrderDetailByDTO(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteOrderDetailById", ReplyAction="http://tempuri.org/IService/DeleteOrderDetailByIdResponse")]
    bool DeleteOrderDetailById(string orderDetailID);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteOrderDetailById", ReplyAction="http://tempuri.org/IService/DeleteOrderDetailByIdResponse")]
    System.IAsyncResult BeginDeleteOrderDetailById(string orderDetailID, System.AsyncCallback callback, object asyncState);
    
    bool EndDeleteOrderDetailById(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/UpdateOrderDetailByDTO", ReplyAction="http://tempuri.org/IService/UpdateOrderDetailByDTOResponse")]
    bool UpdateOrderDetailByDTO(DTO.OrderDetailDTO newInfo);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/UpdateOrderDetailByDTO", ReplyAction="http://tempuri.org/IService/UpdateOrderDetailByDTOResponse")]
    System.IAsyncResult BeginUpdateOrderDetailByDTO(DTO.OrderDetailDTO newInfo, System.AsyncCallback callback, object asyncState);
    
    bool EndUpdateOrderDetailByDTO(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectOrderDetailByDTO", ReplyAction="http://tempuri.org/IService/SelectOrderDetailByDTOResponse")]
    DTO.OrderDetailDTO[] SelectOrderDetailByDTO(DTO.OrderDetailDTO orderDetailDTO);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectOrderDetailByDTO", ReplyAction="http://tempuri.org/IService/SelectOrderDetailByDTOResponse")]
    System.IAsyncResult BeginSelectOrderDetailByDTO(DTO.OrderDetailDTO orderDetailDTO, System.AsyncCallback callback, object asyncState);
    
    DTO.OrderDetailDTO[] EndSelectOrderDetailByDTO(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceCallback
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/NewOrderInCallback")]
    void NewOrderInCallback();
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/NewOrderInCallback")]
    System.IAsyncResult BeginNewOrderInCallback(System.AsyncCallback callback, object asyncState);
    
    void EndNewOrderInCallback(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/ConfirmOrderInCallback")]
    void ConfirmOrderInCallback();
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/ConfirmOrderInCallback")]
    System.IAsyncResult BeginConfirmOrderInCallback(System.AsyncCallback callback, object asyncState);
    
    void EndConfirmOrderInCallback(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/PaymentInCallback")]
    void PaymentInCallback();
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/PaymentInCallback")]
    System.IAsyncResult BeginPaymentInCallback(System.AsyncCallback callback, object asyncState);
    
    void EndPaymentInCallback(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceChannel : IService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceClient : System.ServiceModel.DuplexClientBase<IService>, IService
{
    
    public ServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public DTO.OrderDetailDTO[] SelectOrderDetailById(string orderId, string foodId)
    {
        return base.Channel.SelectOrderDetailById(orderId, foodId);
    }
    
    public System.IAsyncResult BeginSelectOrderDetailById(string orderId, string foodId, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSelectOrderDetailById(orderId, foodId, callback, asyncState);
    }
    
    public DTO.OrderDetailDTO[] EndSelectOrderDetailById(System.IAsyncResult result)
    {
        return base.Channel.EndSelectOrderDetailById(result);
    }
    
    public bool addBill(DTO.BillDTO billDTO)
    {
        return base.Channel.addBill(billDTO);
    }
    
    public System.IAsyncResult BeginaddBill(DTO.BillDTO billDTO, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginaddBill(billDTO, callback, asyncState);
    }
    
    public bool EndaddBill(System.IAsyncResult result)
    {
        return base.Channel.EndaddBill(result);
    }
    
    public bool DeleteBillByDTO(DTO.BillDTO billDTO)
    {
        return base.Channel.DeleteBillByDTO(billDTO);
    }
    
    public System.IAsyncResult BeginDeleteBillByDTO(DTO.BillDTO billDTO, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginDeleteBillByDTO(billDTO, callback, asyncState);
    }
    
    public bool EndDeleteBillByDTO(System.IAsyncResult result)
    {
        return base.Channel.EndDeleteBillByDTO(result);
    }
    
    public bool DeleteBillById(string billID)
    {
        return base.Channel.DeleteBillById(billID);
    }
    
    public System.IAsyncResult BeginDeleteBillById(string billID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginDeleteBillById(billID, callback, asyncState);
    }
    
    public bool EndDeleteBillById(System.IAsyncResult result)
    {
        return base.Channel.EndDeleteBillById(result);
    }
    
    public DTO.BillDTO[] SelectBillByDTO(DTO.BillDTO billDTO)
    {
        return base.Channel.SelectBillByDTO(billDTO);
    }
    
    public System.IAsyncResult BeginSelectBillByDTO(DTO.BillDTO billDTO, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSelectBillByDTO(billDTO, callback, asyncState);
    }
    
    public DTO.BillDTO[] EndSelectBillByDTO(System.IAsyncResult result)
    {
        return base.Channel.EndSelectBillByDTO(result);
    }
    
    public DTO.BillDTO[] SelectBillById(string billID)
    {
        return base.Channel.SelectBillById(billID);
    }
    
    public System.IAsyncResult BeginSelectBillById(string billID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSelectBillById(billID, callback, asyncState);
    }
    
    public DTO.BillDTO[] EndSelectBillById(System.IAsyncResult result)
    {
        return base.Channel.EndSelectBillById(result);
    }
    
    public string[] getEmpIdAndPermission(string username, string password)
    {
        return base.Channel.getEmpIdAndPermission(username, password);
    }
    
    public System.IAsyncResult BegingetEmpIdAndPermission(string username, string password, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BegingetEmpIdAndPermission(username, password, callback, asyncState);
    }
    
    public string[] EndgetEmpIdAndPermission(System.IAsyncResult result)
    {
        return base.Channel.EndgetEmpIdAndPermission(result);
    }
    
    public string getPermission(string empId)
    {
        return base.Channel.getPermission(empId);
    }
    
    public System.IAsyncResult BegingetPermission(string empId, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BegingetPermission(empId, callback, asyncState);
    }
    
    public string EndgetPermission(System.IAsyncResult result)
    {
        return base.Channel.EndgetPermission(result);
    }
    
    public DTO.OrderFoodDTO[] viewFoodDetail(string orderID)
    {
        return base.Channel.viewFoodDetail(orderID);
    }
    
    public System.IAsyncResult BeginviewFoodDetail(string orderID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginviewFoodDetail(orderID, callback, asyncState);
    }
    
    public DTO.OrderFoodDTO[] EndviewFoodDetail(System.IAsyncResult result)
    {
        return base.Channel.EndviewFoodDetail(result);
    }
    
    public DTO.OrderDTO viewOrderInfo(int tableNum)
    {
        return base.Channel.viewOrderInfo(tableNum);
    }
    
    public System.IAsyncResult BeginviewOrderInfo(int tableNum, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginviewOrderInfo(tableNum, callback, asyncState);
    }
    
    public DTO.OrderDTO EndviewOrderInfo(System.IAsyncResult result)
    {
        return base.Channel.EndviewOrderInfo(result);
    }
    
    public DTO.OrderDTO[] getUnfreeTable(int floorNum)
    {
        return base.Channel.getUnfreeTable(floorNum);
    }
    
    public System.IAsyncResult BegingetUnfreeTable(int floorNum, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BegingetUnfreeTable(floorNum, callback, asyncState);
    }
    
    public DTO.OrderDTO[] EndgetUnfreeTable(System.IAsyncResult result)
    {
        return base.Channel.EndgetUnfreeTable(result);
    }
    
    public string getEmployeeName(string empID)
    {
        return base.Channel.getEmployeeName(empID);
    }
    
    public System.IAsyncResult BegingetEmployeeName(string empID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BegingetEmployeeName(empID, callback, asyncState);
    }
    
    public string EndgetEmployeeName(System.IAsyncResult result)
    {
        return base.Channel.EndgetEmployeeName(result);
    }
    
    public int getTotalOfDay(System.DateTime billDate)
    {
        return base.Channel.getTotalOfDay(billDate);
    }
    
    public System.IAsyncResult BegingetTotalOfDay(System.DateTime billDate, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BegingetTotalOfDay(billDate, callback, asyncState);
    }
    
    public int EndgetTotalOfDay(System.IAsyncResult result)
    {
        return base.Channel.EndgetTotalOfDay(result);
    }
    
    public DTO.DailyReportDTO[] getDailyReport(System.DateTime billDate)
    {
        return base.Channel.getDailyReport(billDate);
    }
    
    public System.IAsyncResult BegingetDailyReport(System.DateTime billDate, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BegingetDailyReport(billDate, callback, asyncState);
    }
    
    public DTO.DailyReportDTO[] EndgetDailyReport(System.IAsyncResult result)
    {
        return base.Channel.EndgetDailyReport(result);
    }
    
    public int getTotalOfMonth(System.DateTime billDate)
    {
        return base.Channel.getTotalOfMonth(billDate);
    }
    
    public System.IAsyncResult BegingetTotalOfMonth(System.DateTime billDate, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BegingetTotalOfMonth(billDate, callback, asyncState);
    }
    
    public int EndgetTotalOfMonth(System.IAsyncResult result)
    {
        return base.Channel.EndgetTotalOfMonth(result);
    }
    
    public DTO.MonthlyReportDTO[] getMonthlyReport(System.DateTime billDate)
    {
        return base.Channel.getMonthlyReport(billDate);
    }
    
    public System.IAsyncResult BegingetMonthlyReport(System.DateTime billDate, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BegingetMonthlyReport(billDate, callback, asyncState);
    }
    
    public DTO.MonthlyReportDTO[] EndgetMonthlyReport(System.IAsyncResult result)
    {
        return base.Channel.EndgetMonthlyReport(result);
    }
    
    public int getTotalOfYear(System.DateTime billDate)
    {
        return base.Channel.getTotalOfYear(billDate);
    }
    
    public System.IAsyncResult BegingetTotalOfYear(System.DateTime billDate, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BegingetTotalOfYear(billDate, callback, asyncState);
    }
    
    public int EndgetTotalOfYear(System.IAsyncResult result)
    {
        return base.Channel.EndgetTotalOfYear(result);
    }
    
    public DTO.YearlyReportDTO[] getYearlyReport(System.DateTime billDate)
    {
        return base.Channel.getYearlyReport(billDate);
    }
    
    public System.IAsyncResult BegingetYearlyReport(System.DateTime billDate, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BegingetYearlyReport(billDate, callback, asyncState);
    }
    
    public DTO.YearlyReportDTO[] EndgetYearlyReport(System.IAsyncResult result)
    {
        return base.Channel.EndgetYearlyReport(result);
    }
    
    public bool connect(DTO.ClientDTO client)
    {
        return base.Channel.connect(client);
    }
    
    public System.IAsyncResult Beginconnect(DTO.ClientDTO client, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.Beginconnect(client, callback, asyncState);
    }
    
    public bool Endconnect(System.IAsyncResult result)
    {
        return base.Channel.Endconnect(result);
    }
    
    public void NewOrderInService()
    {
        base.Channel.NewOrderInService();
    }
    
    public System.IAsyncResult BeginNewOrderInService(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginNewOrderInService(callback, asyncState);
    }
    
    public void EndNewOrderInService(System.IAsyncResult result)
    {
        base.Channel.EndNewOrderInService(result);
    }
    
    public bool addFood(DTO.FoodDTO foodDTO)
    {
        return base.Channel.addFood(foodDTO);
    }
    
    public System.IAsyncResult BeginaddFood(DTO.FoodDTO foodDTO, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginaddFood(foodDTO, callback, asyncState);
    }
    
    public bool EndaddFood(System.IAsyncResult result)
    {
        return base.Channel.EndaddFood(result);
    }
    
    public bool DeleteFoodByDTO(DTO.FoodDTO foodDTO)
    {
        return base.Channel.DeleteFoodByDTO(foodDTO);
    }
    
    public System.IAsyncResult BeginDeleteFoodByDTO(DTO.FoodDTO foodDTO, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginDeleteFoodByDTO(foodDTO, callback, asyncState);
    }
    
    public bool EndDeleteFoodByDTO(System.IAsyncResult result)
    {
        return base.Channel.EndDeleteFoodByDTO(result);
    }
    
    public bool DeleteFoodByID(string foodID)
    {
        return base.Channel.DeleteFoodByID(foodID);
    }
    
    public System.IAsyncResult BeginDeleteFoodByID(string foodID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginDeleteFoodByID(foodID, callback, asyncState);
    }
    
    public bool EndDeleteFoodByID(System.IAsyncResult result)
    {
        return base.Channel.EndDeleteFoodByID(result);
    }
    
    public bool updateFood(DTO.FoodDTO newInfo)
    {
        return base.Channel.updateFood(newInfo);
    }
    
    public System.IAsyncResult BeginupdateFood(DTO.FoodDTO newInfo, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginupdateFood(newInfo, callback, asyncState);
    }
    
    public bool EndupdateFood(System.IAsyncResult result)
    {
        return base.Channel.EndupdateFood(result);
    }
    
    public DTO.FoodDTO[] SelectFoodByDTO(DTO.FoodDTO foodDTO)
    {
        return base.Channel.SelectFoodByDTO(foodDTO);
    }
    
    public System.IAsyncResult BeginSelectFoodByDTO(DTO.FoodDTO foodDTO, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSelectFoodByDTO(foodDTO, callback, asyncState);
    }
    
    public DTO.FoodDTO[] EndSelectFoodByDTO(System.IAsyncResult result)
    {
        return base.Channel.EndSelectFoodByDTO(result);
    }
    
    public DTO.FoodDTO[] SelectFoodById(string foodID)
    {
        return base.Channel.SelectFoodById(foodID);
    }
    
    public System.IAsyncResult BeginSelectFoodById(string foodID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSelectFoodById(foodID, callback, asyncState);
    }
    
    public DTO.FoodDTO[] EndSelectFoodById(System.IAsyncResult result)
    {
        return base.Channel.EndSelectFoodById(result);
    }
    
    public bool addFoodGroup(DTO.FoodGroupDTO foodGroupDTO)
    {
        return base.Channel.addFoodGroup(foodGroupDTO);
    }
    
    public System.IAsyncResult BeginaddFoodGroup(DTO.FoodGroupDTO foodGroupDTO, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginaddFoodGroup(foodGroupDTO, callback, asyncState);
    }
    
    public bool EndaddFoodGroup(System.IAsyncResult result)
    {
        return base.Channel.EndaddFoodGroup(result);
    }
    
    public bool DeleteFoodGroupByDTO(DTO.FoodGroupDTO foodGroupDTO)
    {
        return base.Channel.DeleteFoodGroupByDTO(foodGroupDTO);
    }
    
    public System.IAsyncResult BeginDeleteFoodGroupByDTO(DTO.FoodGroupDTO foodGroupDTO, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginDeleteFoodGroupByDTO(foodGroupDTO, callback, asyncState);
    }
    
    public bool EndDeleteFoodGroupByDTO(System.IAsyncResult result)
    {
        return base.Channel.EndDeleteFoodGroupByDTO(result);
    }
    
    public bool DeleteFoodGroupById(string foodGroupID)
    {
        return base.Channel.DeleteFoodGroupById(foodGroupID);
    }
    
    public System.IAsyncResult BeginDeleteFoodGroupById(string foodGroupID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginDeleteFoodGroupById(foodGroupID, callback, asyncState);
    }
    
    public bool EndDeleteFoodGroupById(System.IAsyncResult result)
    {
        return base.Channel.EndDeleteFoodGroupById(result);
    }
    
    public bool updateFoodGroup(DTO.FoodGroupDTO newInfo)
    {
        return base.Channel.updateFoodGroup(newInfo);
    }
    
    public System.IAsyncResult BeginupdateFoodGroup(DTO.FoodGroupDTO newInfo, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginupdateFoodGroup(newInfo, callback, asyncState);
    }
    
    public bool EndupdateFoodGroup(System.IAsyncResult result)
    {
        return base.Channel.EndupdateFoodGroup(result);
    }
    
    public DTO.FoodGroupDTO[] SelectFoodGroupByDTO(DTO.FoodGroupDTO foodGroupDTO)
    {
        return base.Channel.SelectFoodGroupByDTO(foodGroupDTO);
    }
    
    public System.IAsyncResult BeginSelectFoodGroupByDTO(DTO.FoodGroupDTO foodGroupDTO, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSelectFoodGroupByDTO(foodGroupDTO, callback, asyncState);
    }
    
    public DTO.FoodGroupDTO[] EndSelectFoodGroupByDTO(System.IAsyncResult result)
    {
        return base.Channel.EndSelectFoodGroupByDTO(result);
    }
    
    public DTO.FoodGroupDTO[] SelectFoodGroupById(string foodGroupID)
    {
        return base.Channel.SelectFoodGroupById(foodGroupID);
    }
    
    public System.IAsyncResult BeginSelectFoodGroupById(string foodGroupID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSelectFoodGroupById(foodGroupID, callback, asyncState);
    }
    
    public DTO.FoodGroupDTO[] EndSelectFoodGroupById(System.IAsyncResult result)
    {
        return base.Channel.EndSelectFoodGroupById(result);
    }
    
    public bool addOrder(DTO.OrderDTO orderDTO)
    {
        return base.Channel.addOrder(orderDTO);
    }
    
    public System.IAsyncResult BeginaddOrder(DTO.OrderDTO orderDTO, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginaddOrder(orderDTO, callback, asyncState);
    }
    
    public bool EndaddOrder(System.IAsyncResult result)
    {
        return base.Channel.EndaddOrder(result);
    }
    
    public bool DeleteOrderByDTO(DTO.OrderDTO orderDTO)
    {
        return base.Channel.DeleteOrderByDTO(orderDTO);
    }
    
    public System.IAsyncResult BeginDeleteOrderByDTO(DTO.OrderDTO orderDTO, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginDeleteOrderByDTO(orderDTO, callback, asyncState);
    }
    
    public bool EndDeleteOrderByDTO(System.IAsyncResult result)
    {
        return base.Channel.EndDeleteOrderByDTO(result);
    }
    
    public bool DeleteOrderById(string orderID)
    {
        return base.Channel.DeleteOrderById(orderID);
    }
    
    public System.IAsyncResult BeginDeleteOrderById(string orderID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginDeleteOrderById(orderID, callback, asyncState);
    }
    
    public bool EndDeleteOrderById(System.IAsyncResult result)
    {
        return base.Channel.EndDeleteOrderById(result);
    }
    
    public bool updateOrder(DTO.OrderDTO newInfo)
    {
        return base.Channel.updateOrder(newInfo);
    }
    
    public System.IAsyncResult BeginupdateOrder(DTO.OrderDTO newInfo, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginupdateOrder(newInfo, callback, asyncState);
    }
    
    public bool EndupdateOrder(System.IAsyncResult result)
    {
        return base.Channel.EndupdateOrder(result);
    }
    
    public DTO.OrderDTO[] SelectOrderByDTO(DTO.OrderDTO orderDTO)
    {
        return base.Channel.SelectOrderByDTO(orderDTO);
    }
    
    public System.IAsyncResult BeginSelectOrderByDTO(DTO.OrderDTO orderDTO, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSelectOrderByDTO(orderDTO, callback, asyncState);
    }
    
    public DTO.OrderDTO[] EndSelectOrderByDTO(System.IAsyncResult result)
    {
        return base.Channel.EndSelectOrderByDTO(result);
    }
    
    public DTO.OrderDTO[] SelectOrderById(string orderID)
    {
        return base.Channel.SelectOrderById(orderID);
    }
    
    public System.IAsyncResult BeginSelectOrderById(string orderID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSelectOrderById(orderID, callback, asyncState);
    }
    
    public DTO.OrderDTO[] EndSelectOrderById(System.IAsyncResult result)
    {
        return base.Channel.EndSelectOrderById(result);
    }
    
    public bool addOrderDetail(DTO.OrderDetailDTO orderDetailDTO)
    {
        return base.Channel.addOrderDetail(orderDetailDTO);
    }
    
    public System.IAsyncResult BeginaddOrderDetail(DTO.OrderDetailDTO orderDetailDTO, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginaddOrderDetail(orderDetailDTO, callback, asyncState);
    }
    
    public bool EndaddOrderDetail(System.IAsyncResult result)
    {
        return base.Channel.EndaddOrderDetail(result);
    }
    
    public bool DeleteOrderDetailByDTO(DTO.OrderDetailDTO orderDetailDTO)
    {
        return base.Channel.DeleteOrderDetailByDTO(orderDetailDTO);
    }
    
    public System.IAsyncResult BeginDeleteOrderDetailByDTO(DTO.OrderDetailDTO orderDetailDTO, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginDeleteOrderDetailByDTO(orderDetailDTO, callback, asyncState);
    }
    
    public bool EndDeleteOrderDetailByDTO(System.IAsyncResult result)
    {
        return base.Channel.EndDeleteOrderDetailByDTO(result);
    }
    
    public bool DeleteOrderDetailById(string orderDetailID)
    {
        return base.Channel.DeleteOrderDetailById(orderDetailID);
    }
    
    public System.IAsyncResult BeginDeleteOrderDetailById(string orderDetailID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginDeleteOrderDetailById(orderDetailID, callback, asyncState);
    }
    
    public bool EndDeleteOrderDetailById(System.IAsyncResult result)
    {
        return base.Channel.EndDeleteOrderDetailById(result);
    }
    
    public bool UpdateOrderDetailByDTO(DTO.OrderDetailDTO newInfo)
    {
        return base.Channel.UpdateOrderDetailByDTO(newInfo);
    }
    
    public System.IAsyncResult BeginUpdateOrderDetailByDTO(DTO.OrderDetailDTO newInfo, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginUpdateOrderDetailByDTO(newInfo, callback, asyncState);
    }
    
    public bool EndUpdateOrderDetailByDTO(System.IAsyncResult result)
    {
        return base.Channel.EndUpdateOrderDetailByDTO(result);
    }
    
    public DTO.OrderDetailDTO[] SelectOrderDetailByDTO(DTO.OrderDetailDTO orderDetailDTO)
    {
        return base.Channel.SelectOrderDetailByDTO(orderDetailDTO);
    }
    
    public System.IAsyncResult BeginSelectOrderDetailByDTO(DTO.OrderDetailDTO orderDetailDTO, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSelectOrderDetailByDTO(orderDetailDTO, callback, asyncState);
    }
    
    public DTO.OrderDetailDTO[] EndSelectOrderDetailByDTO(System.IAsyncResult result)
    {
        return base.Channel.EndSelectOrderDetailByDTO(result);
    }
}
