//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class BillDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime BillDateField;
        
        private string BillIDField;
        
        private int BillStatusField;
        
        private string DeleteNodeField;
        
        private string EmpIDField;
        
        private string OrderIDField;
        
        private float TotalField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BillDate
        {
            get
            {
                return this.BillDateField;
            }
            set
            {
                this.BillDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillID
        {
            get
            {
                return this.BillIDField;
            }
            set
            {
                this.BillIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BillStatus
        {
            get
            {
                return this.BillStatusField;
            }
            set
            {
                this.BillStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeleteNode
        {
            get
            {
                return this.DeleteNodeField;
            }
            set
            {
                this.DeleteNodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpID
        {
            get
            {
                return this.EmpIDField;
            }
            set
            {
                this.EmpIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoodDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class FoodDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private float DiscountPriceField;
        
        private string FoodGroupIDField;
        
        private string FoodIDField;
        
        private string FoodNameField;
        
        private float FoodPriceField;
        
        private string ImageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float DiscountPrice
        {
            get
            {
                return this.DiscountPriceField;
            }
            set
            {
                this.DiscountPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodGroupID
        {
            get
            {
                return this.FoodGroupIDField;
            }
            set
            {
                this.FoodGroupIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodID
        {
            get
            {
                return this.FoodIDField;
            }
            set
            {
                this.FoodIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodName
        {
            get
            {
                return this.FoodNameField;
            }
            set
            {
                this.FoodNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FoodPrice
        {
            get
            {
                return this.FoodPriceField;
            }
            set
            {
                this.FoodPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                this.ImageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoodGroupDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class FoodGroupDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FoodGroupIDField;
        
        private string FoodGroupNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodGroupID
        {
            get
            {
                return this.FoodGroupIDField;
            }
            set
            {
                this.FoodGroupIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodGroupName
        {
            get
            {
                return this.FoodGroupNameField;
            }
            set
            {
                this.FoodGroupNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class OrderDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime OrderDateField;
        
        private string OrderIDField;
        
        private string OrderNoteField;
        
        private int OrderStatusField;
        
        private int TableNumField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate
        {
            get
            {
                return this.OrderDateField;
            }
            set
            {
                this.OrderDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNote
        {
            get
            {
                return this.OrderNoteField;
            }
            set
            {
                this.OrderNoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderStatus
        {
            get
            {
                return this.OrderStatusField;
            }
            set
            {
                this.OrderStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TableNum
        {
            get
            {
                return this.TableNumField;
            }
            set
            {
                this.TableNumField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    public partial class OrderDetailDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime CompleteTimeField;
        
        private string FoodIDField;
        
        private string FoodNoteField;
        
        private string OrderIDField;
        
        private int PriorityField;
        
        private int QuantityField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CompleteTime
        {
            get
            {
                return this.CompleteTimeField;
            }
            set
            {
                this.CompleteTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodID
        {
            get
            {
                return this.FoodIDField;
            }
            set
            {
                this.FoodIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodNote
        {
            get
            {
                return this.FoodNoteField;
            }
            set
            {
                this.FoodNoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority
        {
            get
            {
                return this.PriorityField;
            }
            set
            {
                this.PriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService")]
public interface IService
{
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectBillByDTO", ReplyAction="http://tempuri.org/IService/SelectBillByDTOResponse")]
    DTO.BillDTO[] SelectBillByDTO(DTO.BillDTO billDTO);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectBillById", ReplyAction="http://tempuri.org/IService/SelectBillByIdResponse")]
    DTO.BillDTO[] SelectBillById(string billID);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addFood", ReplyAction="http://tempuri.org/IService/addFoodResponse")]
    bool addFood(DTO.FoodDTO foodDTO);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteFoodByDTO", ReplyAction="http://tempuri.org/IService/DeleteFoodByDTOResponse")]
    bool DeleteFoodByDTO(DTO.FoodDTO foodDTO);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteFoodByID", ReplyAction="http://tempuri.org/IService/DeleteFoodByIDResponse")]
    bool DeleteFoodByID(string foodID);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/updateFood", ReplyAction="http://tempuri.org/IService/updateFoodResponse")]
    bool updateFood(DTO.FoodDTO newInfo);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectFoodByDTO", ReplyAction="http://tempuri.org/IService/SelectFoodByDTOResponse")]
    DTO.FoodDTO[] SelectFoodByDTO(DTO.FoodDTO foodDTO);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectFoodById", ReplyAction="http://tempuri.org/IService/SelectFoodByIdResponse")]
    DTO.FoodDTO[] SelectFoodById(string foodID);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addFoodGroup", ReplyAction="http://tempuri.org/IService/addFoodGroupResponse")]
    bool addFoodGroup(DTO.FoodGroupDTO foodGroupDTO);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteFoodGroupByDTO", ReplyAction="http://tempuri.org/IService/DeleteFoodGroupByDTOResponse")]
    bool DeleteFoodGroupByDTO(DTO.FoodGroupDTO foodGroupDTO);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteFoodGroupById", ReplyAction="http://tempuri.org/IService/DeleteFoodGroupByIdResponse")]
    bool DeleteFoodGroupById(string foodGroupID);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/updateFoodGroup", ReplyAction="http://tempuri.org/IService/updateFoodGroupResponse")]
    bool updateFoodGroup(DTO.FoodGroupDTO newInfo);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectFoodGroupByDTO", ReplyAction="http://tempuri.org/IService/SelectFoodGroupByDTOResponse")]
    DTO.FoodGroupDTO[] SelectFoodGroupByDTO(DTO.FoodGroupDTO foodGroupDTO);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectFoodGroupById", ReplyAction="http://tempuri.org/IService/SelectFoodGroupByIdResponse")]
    DTO.FoodGroupDTO[] SelectFoodGroupById(string foodGroupID);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addOrder", ReplyAction="http://tempuri.org/IService/addOrderResponse")]
    bool addOrder(DTO.OrderDTO orderDTO);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteOrderByDTO", ReplyAction="http://tempuri.org/IService/DeleteOrderByDTOResponse")]
    bool DeleteOrderByDTO(DTO.OrderDTO orderDTO);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteOrderById", ReplyAction="http://tempuri.org/IService/DeleteOrderByIdResponse")]
    bool DeleteOrderById(string orderID);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/updateOrder", ReplyAction="http://tempuri.org/IService/updateOrderResponse")]
    bool updateOrder(DTO.OrderDTO newInfo);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectOrderByDTO", ReplyAction="http://tempuri.org/IService/SelectOrderByDTOResponse")]
    DTO.OrderDTO[] SelectOrderByDTO(DTO.OrderDTO orderDTO);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectOrderById", ReplyAction="http://tempuri.org/IService/SelectOrderByIdResponse")]
    DTO.OrderDTO[] SelectOrderById(string orderID);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addOrderDetail", ReplyAction="http://tempuri.org/IService/addOrderDetailResponse")]
    bool addOrderDetail(DTO.OrderDetailDTO orderDetailDTO);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteOrderDetailByDTO", ReplyAction="http://tempuri.org/IService/DeleteOrderDetailByDTOResponse")]
    bool DeleteOrderDetailByDTO(DTO.OrderDetailDTO orderDetailDTO);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteOrderDetailById", ReplyAction="http://tempuri.org/IService/DeleteOrderDetailByIdResponse")]
    bool DeleteOrderDetailById(string orderDetailID);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/UpdateOrderDetailByDTO", ReplyAction="http://tempuri.org/IService/UpdateOrderDetailByDTOResponse")]
    bool UpdateOrderDetailByDTO(DTO.OrderDetailDTO newInfo);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectOrderDetailByDTO", ReplyAction="http://tempuri.org/IService/SelectOrderDetailByDTOResponse")]
    DTO.OrderDetailDTO[] SelectOrderDetailByDTO(DTO.OrderDetailDTO orderDetailDTO);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectOrderDetailById", ReplyAction="http://tempuri.org/IService/SelectOrderDetailByIdResponse")]
    DTO.OrderDetailDTO[] SelectOrderDetailById(string orderId, string foodId);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addBill", ReplyAction="http://tempuri.org/IService/addBillResponse")]
    bool addBill(DTO.BillDTO billDTO);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteBillByDTO", ReplyAction="http://tempuri.org/IService/DeleteBillByDTOResponse")]
    bool DeleteBillByDTO(DTO.BillDTO billDTO);
    
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteBillById", ReplyAction="http://tempuri.org/IService/DeleteBillByIdResponse")]
    bool DeleteBillById(string billID);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceChannel : IService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceClient : System.ServiceModel.ClientBase<IService>, IService
{
    
    public ServiceClient()
    {
    }
    
    public ServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public DTO.BillDTO[] SelectBillByDTO(DTO.BillDTO billDTO)
    {
        return base.Channel.SelectBillByDTO(billDTO);
    }
    
    public DTO.BillDTO[] SelectBillById(string billID)
    {
        return base.Channel.SelectBillById(billID);
    }
    
    public bool addFood(DTO.FoodDTO foodDTO)
    {
        return base.Channel.addFood(foodDTO);
    }
    
    public bool DeleteFoodByDTO(DTO.FoodDTO foodDTO)
    {
        return base.Channel.DeleteFoodByDTO(foodDTO);
    }
    
    public bool DeleteFoodByID(string foodID)
    {
        return base.Channel.DeleteFoodByID(foodID);
    }
    
    public bool updateFood(DTO.FoodDTO newInfo)
    {
        return base.Channel.updateFood(newInfo);
    }
    
    public DTO.FoodDTO[] SelectFoodByDTO(DTO.FoodDTO foodDTO)
    {
        return base.Channel.SelectFoodByDTO(foodDTO);
    }
    
    public DTO.FoodDTO[] SelectFoodById(string foodID)
    {
        return base.Channel.SelectFoodById(foodID);
    }
    
    public bool addFoodGroup(DTO.FoodGroupDTO foodGroupDTO)
    {
        return base.Channel.addFoodGroup(foodGroupDTO);
    }
    
    public bool DeleteFoodGroupByDTO(DTO.FoodGroupDTO foodGroupDTO)
    {
        return base.Channel.DeleteFoodGroupByDTO(foodGroupDTO);
    }
    
    public bool DeleteFoodGroupById(string foodGroupID)
    {
        return base.Channel.DeleteFoodGroupById(foodGroupID);
    }
    
    public bool updateFoodGroup(DTO.FoodGroupDTO newInfo)
    {
        return base.Channel.updateFoodGroup(newInfo);
    }
    
    public DTO.FoodGroupDTO[] SelectFoodGroupByDTO(DTO.FoodGroupDTO foodGroupDTO)
    {
        return base.Channel.SelectFoodGroupByDTO(foodGroupDTO);
    }
    
    public DTO.FoodGroupDTO[] SelectFoodGroupById(string foodGroupID)
    {
        return base.Channel.SelectFoodGroupById(foodGroupID);
    }
    
    public bool addOrder(DTO.OrderDTO orderDTO)
    {
        return base.Channel.addOrder(orderDTO);
    }
    
    public bool DeleteOrderByDTO(DTO.OrderDTO orderDTO)
    {
        return base.Channel.DeleteOrderByDTO(orderDTO);
    }
    
    public bool DeleteOrderById(string orderID)
    {
        return base.Channel.DeleteOrderById(orderID);
    }
    
    public bool updateOrder(DTO.OrderDTO newInfo)
    {
        return base.Channel.updateOrder(newInfo);
    }
    
    public DTO.OrderDTO[] SelectOrderByDTO(DTO.OrderDTO orderDTO)
    {
        return base.Channel.SelectOrderByDTO(orderDTO);
    }
    
    public DTO.OrderDTO[] SelectOrderById(string orderID)
    {
        return base.Channel.SelectOrderById(orderID);
    }
    
    public bool addOrderDetail(DTO.OrderDetailDTO orderDetailDTO)
    {
        return base.Channel.addOrderDetail(orderDetailDTO);
    }
    
    public bool DeleteOrderDetailByDTO(DTO.OrderDetailDTO orderDetailDTO)
    {
        return base.Channel.DeleteOrderDetailByDTO(orderDetailDTO);
    }
    
    public bool DeleteOrderDetailById(string orderDetailID)
    {
        return base.Channel.DeleteOrderDetailById(orderDetailID);
    }
    
    public bool UpdateOrderDetailByDTO(DTO.OrderDetailDTO newInfo)
    {
        return base.Channel.UpdateOrderDetailByDTO(newInfo);
    }
    
    public DTO.OrderDetailDTO[] SelectOrderDetailByDTO(DTO.OrderDetailDTO orderDetailDTO)
    {
        return base.Channel.SelectOrderDetailByDTO(orderDetailDTO);
    }
    
    public DTO.OrderDetailDTO[] SelectOrderDetailById(string orderId, string foodId)
    {
        return base.Channel.SelectOrderDetailById(orderId, foodId);
    }
    
    public bool addBill(DTO.BillDTO billDTO)
    {
        return base.Channel.addBill(billDTO);
    }
    
    public bool DeleteBillByDTO(DTO.BillDTO billDTO)
    {
        return base.Channel.DeleteBillByDTO(billDTO);
    }
    
    public bool DeleteBillById(string billID)
    {
        return base.Channel.DeleteBillById(billID);
    }
}
