USE KFC_DB2
GO
ALTER TABLE dbo.FOOD
DROP CONSTRAINT FK_FOOD_FOOD_GROUP

GO
ALTER TABLE dbo.BILL
DROP CONSTRAINT FK_BILL_EMP, FK_BILL_ORDER

GO
ALTER TABLE dbo.ORDER_DETAIL
DROP CONSTRAINT FK_ORDER_DETAIL_ORDER, FK_ORDER_DETAIL_FOOD