//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitchenController.KfcService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class BillDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BillDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BillStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeleteNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BillDate {
            get {
                return this.BillDateField;
            }
            set {
                if ((this.BillDateField.Equals(value) != true)) {
                    this.BillDateField = value;
                    this.RaisePropertyChanged("BillDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillID {
            get {
                return this.BillIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BillIDField, value) != true)) {
                    this.BillIDField = value;
                    this.RaisePropertyChanged("BillID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BillStatus {
            get {
                return this.BillStatusField;
            }
            set {
                if ((this.BillStatusField.Equals(value) != true)) {
                    this.BillStatusField = value;
                    this.RaisePropertyChanged("BillStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeleteNote {
            get {
                return this.DeleteNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.DeleteNoteField, value) != true)) {
                    this.DeleteNoteField = value;
                    this.RaisePropertyChanged("DeleteNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpID {
            get {
                return this.EmpIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpIDField, value) != true)) {
                    this.EmpIDField = value;
                    this.RaisePropertyChanged("EmpID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderFoodDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class OrderFoodDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiscountPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FoodPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiscountPrice {
            get {
                return this.DiscountPriceField;
            }
            set {
                if ((this.DiscountPriceField.Equals(value) != true)) {
                    this.DiscountPriceField = value;
                    this.RaisePropertyChanged("DiscountPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodID {
            get {
                return this.FoodIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodIDField, value) != true)) {
                    this.FoodIDField = value;
                    this.RaisePropertyChanged("FoodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodName {
            get {
                return this.FoodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodNameField, value) != true)) {
                    this.FoodNameField = value;
                    this.RaisePropertyChanged("FoodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FoodPrice {
            get {
                return this.FoodPriceField;
            }
            set {
                if ((this.FoodPriceField.Equals(value) != true)) {
                    this.FoodPriceField = value;
                    this.RaisePropertyChanged("FoodPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class OrderDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TableNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNote {
            get {
                return this.OrderNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNoteField, value) != true)) {
                    this.OrderNoteField = value;
                    this.RaisePropertyChanged("OrderNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((this.OrderStatusField.Equals(value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TableNum {
            get {
                return this.TableNumField;
            }
            set {
                if ((this.TableNumField.Equals(value) != true)) {
                    this.TableNumField = value;
                    this.RaisePropertyChanged("TableNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DailyReportDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class DailyReportDTO : KitchenController.KfcService.ReportDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string foodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string foodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string foodID {
            get {
                return this.foodIDField;
            }
            set {
                if ((object.ReferenceEquals(this.foodIDField, value) != true)) {
                    this.foodIDField = value;
                    this.RaisePropertyChanged("foodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string foodName {
            get {
                return this.foodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.foodNameField, value) != true)) {
                    this.foodNameField = value;
                    this.RaisePropertyChanged("foodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KitchenController.KfcService.MonthlyReportDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KitchenController.KfcService.YearlyReportDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KitchenController.KfcService.DailyReportDTO))]
    public partial class ReportDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonthlyReportDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class MonthlyReportDTO : KitchenController.KfcService.ReportDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string billDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string billDate {
            get {
                return this.billDateField;
            }
            set {
                if ((object.ReferenceEquals(this.billDateField, value) != true)) {
                    this.billDateField = value;
                    this.RaisePropertyChanged("billDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YearlyReportDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class YearlyReportDTO : KitchenController.KfcService.ReportDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string billDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string billDate {
            get {
                return this.billDateField;
            }
            set {
                if ((object.ReferenceEquals(this.billDateField, value) != true)) {
                    this.billDateField = value;
                    this.RaisePropertyChanged("billDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoodDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class FoodDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DiscountPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodGroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FoodPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FoodStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float DiscountPrice {
            get {
                return this.DiscountPriceField;
            }
            set {
                if ((this.DiscountPriceField.Equals(value) != true)) {
                    this.DiscountPriceField = value;
                    this.RaisePropertyChanged("DiscountPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodGroupID {
            get {
                return this.FoodGroupIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodGroupIDField, value) != true)) {
                    this.FoodGroupIDField = value;
                    this.RaisePropertyChanged("FoodGroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodID {
            get {
                return this.FoodIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodIDField, value) != true)) {
                    this.FoodIDField = value;
                    this.RaisePropertyChanged("FoodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodName {
            get {
                return this.FoodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodNameField, value) != true)) {
                    this.FoodNameField = value;
                    this.RaisePropertyChanged("FoodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float FoodPrice {
            get {
                return this.FoodPriceField;
            }
            set {
                if ((this.FoodPriceField.Equals(value) != true)) {
                    this.FoodPriceField = value;
                    this.RaisePropertyChanged("FoodPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FoodStatus {
            get {
                return this.FoodStatusField;
            }
            set {
                if ((this.FoodStatusField.Equals(value) != true)) {
                    this.FoodStatusField = value;
                    this.RaisePropertyChanged("FoodStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoodGroupDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class FoodGroupDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodGroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodGroupNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodGroupID {
            get {
                return this.FoodGroupIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodGroupIDField, value) != true)) {
                    this.FoodGroupIDField = value;
                    this.RaisePropertyChanged("FoodGroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodGroupName {
            get {
                return this.FoodGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodGroupNameField, value) != true)) {
                    this.FoodGroupNameField = value;
                    this.RaisePropertyChanged("FoodGroupName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetailDTO", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class OrderDetailDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CompleteTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FoodNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CompleteTime {
            get {
                return this.CompleteTimeField;
            }
            set {
                if ((this.CompleteTimeField.Equals(value) != true)) {
                    this.CompleteTimeField = value;
                    this.RaisePropertyChanged("CompleteTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodID {
            get {
                return this.FoodIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodIDField, value) != true)) {
                    this.FoodIDField = value;
                    this.RaisePropertyChanged("FoodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FoodNote {
            get {
                return this.FoodNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodNoteField, value) != true)) {
                    this.FoodNoteField = value;
                    this.RaisePropertyChanged("FoodNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KfcService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addBill", ReplyAction="http://tempuri.org/IService/addBillResponse")]
        bool addBill(KitchenController.KfcService.BillDTO billDTO);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteBillByDTO", ReplyAction="http://tempuri.org/IService/DeleteBillByDTOResponse")]
        bool DeleteBillByDTO(KitchenController.KfcService.BillDTO billDTO);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteBillById", ReplyAction="http://tempuri.org/IService/DeleteBillByIdResponse")]
        bool DeleteBillById(string billID);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectBillByDTO", ReplyAction="http://tempuri.org/IService/SelectBillByDTOResponse")]
        KitchenController.KfcService.BillDTO[] SelectBillByDTO(KitchenController.KfcService.BillDTO billDTO);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectBillById", ReplyAction="http://tempuri.org/IService/SelectBillByIdResponse")]
        KitchenController.KfcService.BillDTO[] SelectBillById(string billID);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getEmpIdAndPermission", ReplyAction="http://tempuri.org/IService/getEmpIdAndPermissionResponse")]
        string[] getEmpIdAndPermission(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getPermission", ReplyAction="http://tempuri.org/IService/getPermissionResponse")]
        string getPermission(string empId);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/viewFoodDetail", ReplyAction="http://tempuri.org/IService/viewFoodDetailResponse")]
        KitchenController.KfcService.OrderFoodDTO[] viewFoodDetail(string orderID);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/viewOrderInfo", ReplyAction="http://tempuri.org/IService/viewOrderInfoResponse")]
        KitchenController.KfcService.OrderDTO viewOrderInfo(int tableNum);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getUnfreeTable", ReplyAction="http://tempuri.org/IService/getUnfreeTableResponse")]
        KitchenController.KfcService.OrderDTO[] getUnfreeTable(int floorNum);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getEmployeeName", ReplyAction="http://tempuri.org/IService/getEmployeeNameResponse")]
        string getEmployeeName(string empID);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getTotalOfDay", ReplyAction="http://tempuri.org/IService/getTotalOfDayResponse")]
        int getTotalOfDay(System.DateTime billDate);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getDailyReport", ReplyAction="http://tempuri.org/IService/getDailyReportResponse")]
        KitchenController.KfcService.DailyReportDTO[] getDailyReport(System.DateTime billDate);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getTotalOfMonth", ReplyAction="http://tempuri.org/IService/getTotalOfMonthResponse")]
        int getTotalOfMonth(System.DateTime billDate);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getMonthlyReport", ReplyAction="http://tempuri.org/IService/getMonthlyReportResponse")]
        KitchenController.KfcService.MonthlyReportDTO[] getMonthlyReport(System.DateTime billDate);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getTotalOfYear", ReplyAction="http://tempuri.org/IService/getTotalOfYearResponse")]
        int getTotalOfYear(System.DateTime billDate);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getYearlyReport", ReplyAction="http://tempuri.org/IService/getYearlyReportResponse")]
        KitchenController.KfcService.YearlyReportDTO[] getYearlyReport(System.DateTime billDate);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addFood", ReplyAction="http://tempuri.org/IService/addFoodResponse")]
        bool addFood(KitchenController.KfcService.FoodDTO foodDTO);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteFoodByDTO", ReplyAction="http://tempuri.org/IService/DeleteFoodByDTOResponse")]
        bool DeleteFoodByDTO(KitchenController.KfcService.FoodDTO foodDTO);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteFoodByID", ReplyAction="http://tempuri.org/IService/DeleteFoodByIDResponse")]
        bool DeleteFoodByID(string foodID);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/updateFood", ReplyAction="http://tempuri.org/IService/updateFoodResponse")]
        bool updateFood(KitchenController.KfcService.FoodDTO newInfo);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectFoodByDTO", ReplyAction="http://tempuri.org/IService/SelectFoodByDTOResponse")]
        KitchenController.KfcService.FoodDTO[] SelectFoodByDTO(KitchenController.KfcService.FoodDTO foodDTO);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectFoodById", ReplyAction="http://tempuri.org/IService/SelectFoodByIdResponse")]
        KitchenController.KfcService.FoodDTO[] SelectFoodById(string foodID);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addFoodGroup", ReplyAction="http://tempuri.org/IService/addFoodGroupResponse")]
        bool addFoodGroup(KitchenController.KfcService.FoodGroupDTO foodGroupDTO);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteFoodGroupByDTO", ReplyAction="http://tempuri.org/IService/DeleteFoodGroupByDTOResponse")]
        bool DeleteFoodGroupByDTO(KitchenController.KfcService.FoodGroupDTO foodGroupDTO);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteFoodGroupById", ReplyAction="http://tempuri.org/IService/DeleteFoodGroupByIdResponse")]
        bool DeleteFoodGroupById(string foodGroupID);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/updateFoodGroup", ReplyAction="http://tempuri.org/IService/updateFoodGroupResponse")]
        bool updateFoodGroup(KitchenController.KfcService.FoodGroupDTO newInfo);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectFoodGroupByDTO", ReplyAction="http://tempuri.org/IService/SelectFoodGroupByDTOResponse")]
        KitchenController.KfcService.FoodGroupDTO[] SelectFoodGroupByDTO(KitchenController.KfcService.FoodGroupDTO foodGroupDTO);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectFoodGroupById", ReplyAction="http://tempuri.org/IService/SelectFoodGroupByIdResponse")]
        KitchenController.KfcService.FoodGroupDTO[] SelectFoodGroupById(string foodGroupID);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addOrder", ReplyAction="http://tempuri.org/IService/addOrderResponse")]
        bool addOrder(KitchenController.KfcService.OrderDTO orderDTO);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteOrderByDTO", ReplyAction="http://tempuri.org/IService/DeleteOrderByDTOResponse")]
        bool DeleteOrderByDTO(KitchenController.KfcService.OrderDTO orderDTO);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteOrderById", ReplyAction="http://tempuri.org/IService/DeleteOrderByIdResponse")]
        bool DeleteOrderById(string orderID);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/updateOrder", ReplyAction="http://tempuri.org/IService/updateOrderResponse")]
        bool updateOrder(KitchenController.KfcService.OrderDTO newInfo);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectOrderByDTO", ReplyAction="http://tempuri.org/IService/SelectOrderByDTOResponse")]
        KitchenController.KfcService.OrderDTO[] SelectOrderByDTO(KitchenController.KfcService.OrderDTO orderDTO);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectOrderById", ReplyAction="http://tempuri.org/IService/SelectOrderByIdResponse")]
        KitchenController.KfcService.OrderDTO[] SelectOrderById(string orderID);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/getOrderByStatus", ReplyAction="http://tempuri.org/IService/getOrderByStatusResponse")]
        KitchenController.KfcService.OrderDTO[] getOrderByStatus(string status);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/addOrderDetail", ReplyAction="http://tempuri.org/IService/addOrderDetailResponse")]
        bool addOrderDetail(KitchenController.KfcService.OrderDetailDTO orderDetailDTO);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteOrderDetailByDTO", ReplyAction="http://tempuri.org/IService/DeleteOrderDetailByDTOResponse")]
        bool DeleteOrderDetailByDTO(KitchenController.KfcService.OrderDetailDTO orderDetailDTO);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/DeleteOrderDetailById", ReplyAction="http://tempuri.org/IService/DeleteOrderDetailByIdResponse")]
        bool DeleteOrderDetailById(string orderDetailID);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/UpdateOrderDetailByDTO", ReplyAction="http://tempuri.org/IService/UpdateOrderDetailByDTOResponse")]
        bool UpdateOrderDetailByDTO(KitchenController.KfcService.OrderDetailDTO newInfo);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectOrderDetailByDTO", ReplyAction="http://tempuri.org/IService/SelectOrderDetailByDTOResponse")]
        KitchenController.KfcService.OrderDetailDTO[] SelectOrderDetailByDTO(KitchenController.KfcService.OrderDetailDTO orderDetailDTO);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IService/SelectOrderDetailById", ReplyAction="http://tempuri.org/IService/SelectOrderDetailByIdResponse")]
        KitchenController.KfcService.OrderDetailDTO[] SelectOrderDetailById(string orderId, string foodId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : KitchenController.KfcService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<KitchenController.KfcService.IService>, KitchenController.KfcService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool addBill(KitchenController.KfcService.BillDTO billDTO) {
            return base.Channel.addBill(billDTO);
        }
        
        public bool DeleteBillByDTO(KitchenController.KfcService.BillDTO billDTO) {
            return base.Channel.DeleteBillByDTO(billDTO);
        }
        
        public bool DeleteBillById(string billID) {
            return base.Channel.DeleteBillById(billID);
        }
        
        public KitchenController.KfcService.BillDTO[] SelectBillByDTO(KitchenController.KfcService.BillDTO billDTO) {
            return base.Channel.SelectBillByDTO(billDTO);
        }
        
        public KitchenController.KfcService.BillDTO[] SelectBillById(string billID) {
            return base.Channel.SelectBillById(billID);
        }
        
        public string[] getEmpIdAndPermission(string username, string password) {
            return base.Channel.getEmpIdAndPermission(username, password);
        }
        
        public string getPermission(string empId) {
            return base.Channel.getPermission(empId);
        }
        
        public KitchenController.KfcService.OrderFoodDTO[] viewFoodDetail(string orderID) {
            return base.Channel.viewFoodDetail(orderID);
        }
        
        public KitchenController.KfcService.OrderDTO viewOrderInfo(int tableNum) {
            return base.Channel.viewOrderInfo(tableNum);
        }
        
        public KitchenController.KfcService.OrderDTO[] getUnfreeTable(int floorNum) {
            return base.Channel.getUnfreeTable(floorNum);
        }
        
        public string getEmployeeName(string empID) {
            return base.Channel.getEmployeeName(empID);
        }
        
        public int getTotalOfDay(System.DateTime billDate) {
            return base.Channel.getTotalOfDay(billDate);
        }
        
        public KitchenController.KfcService.DailyReportDTO[] getDailyReport(System.DateTime billDate) {
            return base.Channel.getDailyReport(billDate);
        }
        
        public int getTotalOfMonth(System.DateTime billDate) {
            return base.Channel.getTotalOfMonth(billDate);
        }
        
        public KitchenController.KfcService.MonthlyReportDTO[] getMonthlyReport(System.DateTime billDate) {
            return base.Channel.getMonthlyReport(billDate);
        }
        
        public int getTotalOfYear(System.DateTime billDate) {
            return base.Channel.getTotalOfYear(billDate);
        }
        
        public KitchenController.KfcService.YearlyReportDTO[] getYearlyReport(System.DateTime billDate) {
            return base.Channel.getYearlyReport(billDate);
        }
        
        public bool addFood(KitchenController.KfcService.FoodDTO foodDTO) {
            return base.Channel.addFood(foodDTO);
        }
        
        public bool DeleteFoodByDTO(KitchenController.KfcService.FoodDTO foodDTO) {
            return base.Channel.DeleteFoodByDTO(foodDTO);
        }
        
        public bool DeleteFoodByID(string foodID) {
            return base.Channel.DeleteFoodByID(foodID);
        }
        
        public bool updateFood(KitchenController.KfcService.FoodDTO newInfo) {
            return base.Channel.updateFood(newInfo);
        }
        
        public KitchenController.KfcService.FoodDTO[] SelectFoodByDTO(KitchenController.KfcService.FoodDTO foodDTO) {
            return base.Channel.SelectFoodByDTO(foodDTO);
        }
        
        public KitchenController.KfcService.FoodDTO[] SelectFoodById(string foodID) {
            return base.Channel.SelectFoodById(foodID);
        }
        
        public bool addFoodGroup(KitchenController.KfcService.FoodGroupDTO foodGroupDTO) {
            return base.Channel.addFoodGroup(foodGroupDTO);
        }
        
        public bool DeleteFoodGroupByDTO(KitchenController.KfcService.FoodGroupDTO foodGroupDTO) {
            return base.Channel.DeleteFoodGroupByDTO(foodGroupDTO);
        }
        
        public bool DeleteFoodGroupById(string foodGroupID) {
            return base.Channel.DeleteFoodGroupById(foodGroupID);
        }
        
        public bool updateFoodGroup(KitchenController.KfcService.FoodGroupDTO newInfo) {
            return base.Channel.updateFoodGroup(newInfo);
        }
        
        public KitchenController.KfcService.FoodGroupDTO[] SelectFoodGroupByDTO(KitchenController.KfcService.FoodGroupDTO foodGroupDTO) {
            return base.Channel.SelectFoodGroupByDTO(foodGroupDTO);
        }
        
        public KitchenController.KfcService.FoodGroupDTO[] SelectFoodGroupById(string foodGroupID) {
            return base.Channel.SelectFoodGroupById(foodGroupID);
        }
        
        public bool addOrder(KitchenController.KfcService.OrderDTO orderDTO) {
            return base.Channel.addOrder(orderDTO);
        }
        
        public bool DeleteOrderByDTO(KitchenController.KfcService.OrderDTO orderDTO) {
            return base.Channel.DeleteOrderByDTO(orderDTO);
        }
        
        public bool DeleteOrderById(string orderID) {
            return base.Channel.DeleteOrderById(orderID);
        }
        
        public bool updateOrder(KitchenController.KfcService.OrderDTO newInfo) {
            return base.Channel.updateOrder(newInfo);
        }
        
        public KitchenController.KfcService.OrderDTO[] SelectOrderByDTO(KitchenController.KfcService.OrderDTO orderDTO) {
            return base.Channel.SelectOrderByDTO(orderDTO);
        }
        
        public KitchenController.KfcService.OrderDTO[] SelectOrderById(string orderID) {
            return base.Channel.SelectOrderById(orderID);
        }
        
        public KitchenController.KfcService.OrderDTO[] getOrderByStatus(string status) {
            return base.Channel.getOrderByStatus(status);
        }
        
        public bool addOrderDetail(KitchenController.KfcService.OrderDetailDTO orderDetailDTO) {
            return base.Channel.addOrderDetail(orderDetailDTO);
        }
        
        public bool DeleteOrderDetailByDTO(KitchenController.KfcService.OrderDetailDTO orderDetailDTO) {
            return base.Channel.DeleteOrderDetailByDTO(orderDetailDTO);
        }
        
        public bool DeleteOrderDetailById(string orderDetailID) {
            return base.Channel.DeleteOrderDetailById(orderDetailID);
        }
        
        public bool UpdateOrderDetailByDTO(KitchenController.KfcService.OrderDetailDTO newInfo) {
            return base.Channel.UpdateOrderDetailByDTO(newInfo);
        }
        
        public KitchenController.KfcService.OrderDetailDTO[] SelectOrderDetailByDTO(KitchenController.KfcService.OrderDetailDTO orderDetailDTO) {
            return base.Channel.SelectOrderDetailByDTO(orderDetailDTO);
        }
        
        public KitchenController.KfcService.OrderDetailDTO[] SelectOrderDetailById(string orderId, string foodId) {
            return base.Channel.SelectOrderDetailById(orderId, foodId);
        }
    }
}
